name: quantum-nonogram
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - jupyterlab
  - pip
  - pip:
    - qiskit>=2.2
    - qiskit-algorithms
    - flask
    - flask-socketio
    - numpy
    - matplotlib
    - scipy
    - -e .        # installs the nonogram package in editable mode
